# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bind', max_length=32, verbose_name='昵称')),
                ('head_portrait_width', models.PositiveIntegerField(default=90)),
                ('head_portrait_height', models.PositiveIntegerField(default=90)),
                ('head_portrait', models.ImageField(blank=True, height_field='head_portrait_height', null=True, upload_to='upload/user_image', verbose_name='头像', width_field='head_portrait_width')),
                ('login_status', models.IntegerField(default=0, verbose_name='用户登录状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
