"""
Django settings for BindUI project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

## 如果使用 MySQL 数据库，开启下面几行注释 --start
import pymysql
# 指定 pymysql 的版本。主要是要比 Django 要求的最低版本要大
pymysql.version_info = (11, 1, 0, "final", 0)
pymysql.install_as_MySQLdb()
## 如果使用 MySQL 数据库，开启下面几行注释 --end

# 旧版
# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-51d2pp-e07hhkk=)cchlc_9_td&=sc^r=96_xr_20f=ixk-&5l'

# SECURITY WARNING: don't run with debug turned on in production!
# 如果 DEBUG = False，则 Django 不再代理静态文件。所以访问访问静态资源将报 404 错误
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dns',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bindUI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bindUI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

## MySQL Database 连接信息
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '10.100.240.135',
        'PORT': '3306',
        'NAME': 'dns',
        'USER': 'dns_wr',
        'PASSWORD': 'Ww123456!',
    }
}

## PostgreSQL Database 连接信息
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'HOST': '10.100.240.135',
#         'PORT': '5432',
#         'NAME': 'dns',
#         'USER': 'dns_wr',
#         'PASSWORD': 'Ww123456!',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# format DateTime
USE_L10N = False
DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# 旧版
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR,'static'),
#     os.path.join(BASE_DIR,'upload'),
#
# )

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'upload',
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# models 默认字段 id 的类型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## 生成 ./static/admin 静态资源文件
# django admin静态文件加载不了问题
# 1. 先把 setttings.py 中的 STATICFILES_DIRS 注释
# 2. python3 manage.py collectstatic
#   会生成 ./static/admin 目录
# 3. 完成后，手动恢复 setttings.py 配置
#STATIC_ROOT = os.path.join(BASE_DIR, "static")
#STATICFILES_FINDERS = (
#    "django.contrib.staticfiles.finders.FileSystemFinder",
#    "django.contrib.staticfiles.finders.AppDirectoriesFinder"
#)

# # upstream源站上线前是否需要测试连接源站URL
# UPSTREAM_UP_REALSERVER_TEST = {'test':False, 'url':'/do_not_delete/check.html'}

# 指定全局要求登录的 URL
LOGIN_URL = '/auth/login/'

# 会话超时设置
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 60*60*24*3              # session超时时间。默认是好多天
SESSION_EXPIRE_AT_BROWSER_CLOSE = False   # 会话cookie可以在用户浏览器中保持有效期。True：关闭浏览器，则Cookie失效。