# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnsRecord', '0002_auto_20170802_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='resolution_line',
            field=models.IntegerField(choices=[(0, '默认'), (1, '国内'), (2, '国外'), (3, '电信'), (4, '联通'), (5, '移动'), (6, '教育网')], default=0, help_text='解析线路', verbose_name='resolution_line'),
        ),
    ]
