# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DnsRecord', '0003_record_resolution_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='zone_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ZoneTag_Record', to='DnsRecord.ZoneTag'),
        ),
    ]
