# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DnsRecord', '0004_auto_20170827_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='resolution_line',
        ),
    ]
