# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnsRecord', '0005_remove_record_resolution_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='resolution_line',
            field=models.CharField(choices=[('0', '默认'), ('cn', '国内'), ('abroad', '国外'), ('101', '电信'), ('102', '联通'), ('103', '移动'), ('104', '教育网')], default='0', help_text='解析线路', max_length=32, verbose_name='resolution_line'),
        ),
    ]
