# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnsRecord', '0011_auto_20170906_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='host',
            field=models.CharField(default='@', help_text='Host name or IP address', max_length=255, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('AAAA', 'AAAA'), ('SRV', 'SRV'), ('PTR', 'PTR'), ('SOA', 'SOA')], default='A', help_text='DNS data type', max_length=64, verbose_name='type'),
        ),
    ]
